language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3
  - hhvm

branches:
  only:
    - master

before_script:
  - ./bin/travis/before_script.sh

script:
  - mkdir -p build/logs
  - phpunit --configuration=tests/phpunit.xml
  - ./bin/travis/run_phpcs.sh

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3.3
